baseURL = "https://dengchengsheng.netlify.app/"
languageCode = "en-us"
theme = "sada"
googleAnalytics = "UA-178433381-3" 


[params]
    title = "Chengsheng's Webiste"
    author = "Chengsheng Deng"
    description = "A Student And A Data Enthusiast"
    copyright = ""
    copyright_link = ""

    # Profile section
    [params.profile]
        name = "Chengsheng Deng"
        photo = "images/mypicture.jpg"


    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
        class = "fab"
        icon = "fa-linkedin-in"
        url = "https://www.linkedin.com/in/chengsheng-deng-40b938196/"
        title = "LinkedIn"

        [[params.social.list]]
        class = "fab"
        icon = "fa-github"
        url = "https://github.com/ChengshengDeng"
        title = "GitHub" 
        
        [[params.social.list]]
        class = "fab" 
        icon = "fa-twitter" 
        url = "https://twitter.com/KingDylanDeng"
        title = "Twitter"  
        
        [[params.social.list]]
        class = "fab" 
        icon = "fa-weibo"
        url = "https://dylanphotogallery.netlify.app/"
        title = "Weibo"
		

    # Education section
    [params.education]
        title = "Education"

        [[params.education.list]]
        degree = "Master of Arts in Statistics"
        college = "Boston University"
        dates = "Sep.2019 - Jan.2021"

        [[params.education.list]]
        degree = "Bachelor of Science in Mathematics"
        college = "University of Massachusetts Amherst"
        dates = "Sep.2015 - May.2019" 

    # Languages section
    [params.language]
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Fluent"
				
        [[params.language.list]]
        language = "Mandarin"
        level = "Native"

    # Interests section
    [params.hobbies]
        title = "Hobbies"

        [[params.hobbies.list]]
        interest = "Basketball"
		
		[[params.hobbies.list]]
        interest = "Reading"

        [[params.hobbies.list]]
        interest = "Music"

        [[params.hobbies.list]]
        interest = "Running"
        
        [[params.hobbies.list]]
        interest = "Photography"

    [params.aboutme]
        description = "Hi,welcome to my personal website! My name is Chengsheng Deng, a student pursuing Master degree in Statistics in Boston University. I am also seeking for job opportunities about data science."

    # Experiences section
    [params.experiences]
        icon = "fa-briefcase"
        title = "Experiences" 
        
        [[params.jobs.list]]
        position = "Business Analyst"
        dates = "Jun.2018 - Aug.2018"
        company = "Orient Securities, Shanghai, China"
        details = "1.Negotiated partnerships with some banks such as HSBC, China CITIC Bank, and Citibank.</br> 3.Led reshaping of the strategy, making the new plan launched two weeks earlier than expected.</br>"
        details = "Utilized Tableau to visualize data and propose new strategies to reduce churn rate by 3%."

        [[params.jobs.list]]
        position = "Data Analyst"
        dates = "Jun.2017 - Aug.2017"
        company = "Ciaohu Comapny"
        details = "1.Communicated with clients and collected data for analysis.<br/> 2.Utilized Python to process data including data cleaning, features selection, deleting outliers, transfer data types; ran regression models to do prediction. <br/> 3. Assessed fitness for different models; recommended data-driven solutions to improve sales for next month."
  

    # Projects section
    [params.projects]
        icon = "fa-project-diagram"
        title = "Projects"

        [[params.projects.list]]
        title = "Analysis of Avocados|R"
        url = "https://3r.netlify.com/about/"
        description = "1.Applied data manipulation and visualization to examine fluctuation of avocado’s monthly prices; concluded the prices of avocado in autumn would be about 5 - 10% higher than in spring. 2.Plotted a time series model of monthly prices of avocados from 2015 to 2019 to predict the monthly price next year with over 85% accuracy. 3.Compiled the findings into a website (https://3r.netlify.app/about/)."
		    
		    [[params.projects.list]]
        title = "Analysis of Three Basketball Players|Python " 
        description = "1.Analyzed and manipulated three basketball player’s career data. <br/> 2.Posted a conclusion on the basketball forum and got an 86% support rate. 3.Ran the regression model to predict the salary of one player next season with over 95% accuracy."
        
        [[params.projects.list]]
        title = "Car Analysis|Python" 
        description = "1.Identified critical factors affecting car prices with team members.<br/> 2.Forecasted prices with 3 different statistical models and pinpoint significant features for prices. <br/> 3.Developed some marketing strategies to stimulate the growth of car sales and won second place in the school project competition"
        
        
    # Skills section
    [params.skills]
        icon = "fa-cogs"
        title = "Skills"

        [[params.skills.list]]
        skill = "Python,R,MySQL,Ms Office,Tableau"
                
        
