baseURL = "http://example.org/"
languageCode = "en-us"
theme = "sada"

[params]
    title = "Chengsheng's Webiste"
    author = "Chengsheng Deng"
    description = "A Student And A Data Enthusiast"
    copyright = ""
    copyright_link = ""

    # Profile section
    [params.profile]
        name = "Chengsheng Deng"
        photo = "images/mypicture.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
        class = "fab"
        icon = "fa-linkedin-in"
        url = "https://www.linkedin.com/in/chengsheng-deng-40b938196/"
        title = "LinkedIn"

        [[params.social.list]]
        class = "fab"
        icon = "fa-github"
        url = "https://github.com/ChengshengDeng"
        title = "GitHub"
		

    # Education section
    [params.education]
        title = "Education"

        [[params.education.list]]
        degree = "Master of Arts in Statistics"
        college = "Boston University"
        dates = "Sep.2019 - Dec.2020"

        [[params.education.list]]
        degree = "Bachelor of Science in Mathematics"
        college = "University of Massachusetts Amherst"
        dates = "Sep.2015 - May.2019" 

    # Languages section
    [params.language]
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Fluent"
				
        [[params.language.list]]
        language = "Mandarin"
        level = "Native"

    # Interests section
    [params.hobbies]
        title = "Hobbies"

        [[params.hobbies.list]]
        interest = "Basketball"
		
		[[params.hobbies.list]]
        interest = "Reading"

        [[params.hobbies.list]]
        interest = "Music"

        [[params.hobbies.list]]
        interest = "Running"

    [params.aboutme]
        description = "Hi, welcome to my personal website! My name is Chengsheng Deng, a student pursuing Master degree in Statistics in Boston University. I am also seeking for job opportunities about data analysis."

    # Experiences section
    [params.experiences]
        icon = "fa-briefcase"
        title = "Experiences" 
        
        [[params.jobs.list]]
        position = "Data Analyst"
        dates = "Jun.2018 - Aug.2018"
        company = "Orient Securities, Shanghai, China"
        details = "1.Conducted a research to examine characteristics of Internet Finance and methods finance institutions used to improve financial services.<br/> 2.Utilized Python to perform data extraction and data manipulation and reviewed data to determine market and business trends through statistical modeling. <br/> 3.Selected Ping An bank’s stock and wrote a strategy collaborating with director and a colleague; obtained 5.61% of strategy revenue, 4.43% of benchmark revenue"


        [[params.jobs.list]]
        position = "Data Analyst"
        dates = "Jun.2017 - Aug.2018"
        company = "Ciaohu Comapny"
        details = "1.Communicated with clients and collected data for analysis. 2.Utilized Python to process data including data cleaning, features selection, deleting outliers, transfer data types; ran regression models to do prediction. 3. Assessed fitness for different models; recommended data-driven solutions to improve sales for next month."
  

    # Projects section
    [params.projects]
        icon = "fa-project-diagram"
        title = "Projects"

        [[params.projects.list]]
        title = "Data Analysis of Avocado's Price"
        url = "https://3r.netlify.com/about/"
        description = "Studied the relationship between the avocado's Price and other variables such as location, season, month, size, etc (Please click the link to access this great project)"
		
		    [[params.projects.list]]
        title = "Analysis of Three basketball Players with Python" 
        description = "1.Studied and manipulated three basketball player’s career data. 2.Leveraged Python to pinpoint player had significant impact on team. 3. Organized a meeting once a week to communicate technical problems when processing data. 4.Built and maintained a dashboard in Excel and made presentation to instructor." 
        
        [[params.projects.list]]
        title = "Analysis of The Best Linear Model for Used Car Price with R" 
        description = "1.Analyzed a research report to identify critical factors to affect car’s price.2.Mentored team members to choose variables and do visualization.3.Compiled R to apply linear model with different variables; evaluated fitness of models.4.Led team of 4 members to present conclusion to instructors from different departments."
        
        [[params.projects.list]]
        title = "Data Analysis of Novel-Corna-Virus in China (In Progress)"
        url = "https://supermanr.netlify.com/about/" 
        description = " This is a data analysis for Novel-Corna-Virus which has outbroken in China for several months"
        
    # Skills section
    [params.skills]
        icon = "fa-cogs"
        title = "Skills"

        [[params.skills.list]]
        skill = "Python"
        skillrating = 75 # out of 100
                
        [[params.skills.list]]
        skill = "R"
        skillrating = 90
		
        [[params.skills.list]]
        skill = "SQL"
        skillrating = 85
